language: python
python:
    - "2.7"
install: "pip install -r requirements.txt"
script: 
    - "for f in $(find ./ -type f -not -path '*migrations/*' -name '*.py'); do pep8 --show-source --show-pep8 $f; done"
    - "nosetests -w geolocator/app/tests"
