"""empty message

Revision ID: 19d67dd8a990
Revises: 60f33ee2e61
Create Date: 2015-03-20 18:25:13.519353

"""

# revision identifiers, used by Alembic.
revision = '19d67dd8a990'
down_revision = '60f33ee2e61'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
