"""empty message

Revision ID: 2c83fbafa41e
Revises: 55f8eedef48a
Create Date: 2015-04-23 21:21:53.311798

"""

# revision identifiers, used by Alembic.
revision = '2c83fbafa41e'
down_revision = '55f8eedef48a'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_location_admin1code'), 'location', ['admin1code'], unique=False)
    op.create_index(op.f('ix_location_admin2code'), 'location', ['admin2code'], unique=False)
    op.create_index(op.f('ix_location_countryname'), 'location', ['countryname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_countryname'), table_name='location')
    op.drop_index(op.f('ix_location_admin2code'), table_name='location')
    op.drop_index(op.f('ix_location_admin1code'), table_name='location')
    ### end Alembic commands ###
