"""empty message

Revision ID: 379e08adff58
Revises: 44f268e8839
Create Date: 2015-04-23 21:15:07.190442

"""

# revision identifiers, used by Alembic.
revision = '379e08adff58'
down_revision = '44f268e8839'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_country_info')
    op.drop_table('raw_locations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_locations',
    sa.Column('geonameid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asciiname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alternamtename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('featureclass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('featurecode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('countrycode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cc2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin1code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin2code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin3code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin4code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('population', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('elevation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modificationdate', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('raw_country_info',
    sa.Column('iso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('iso3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isonumeric', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fips', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capital', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('population', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('continent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tld', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currencycode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currencyname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postalcodeformat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postalcoderegex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('languages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geonameid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('neighbours', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('equivalentfipscode', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    ### end Alembic commands ###
