"""empty message

Revision ID: 3ee825681d1d
Revises: 19d67dd8a990
Create Date: 2015-03-20 18:32:13.418976

"""

# revision identifiers, used by Alembic.
revision = '3ee825681d1d'
down_revision = '19d67dd8a990'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
