"""empty message

Revision ID: 44436403ba60
Revises: 2234c35f76aa
Create Date: 2015-02-20 06:03:31.918249

"""

# revision identifiers, used by Alembic.
revision = '44436403ba60'
down_revision = '2234c35f76aa'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_location_location'), 'location', ['location'], unique=False)
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_location'), table_name='location')
    ### end Alembic commands ###
