"""empty message

Revision ID: 55f8eedef48a
Revises: 379e08adff58
Create Date: 2015-04-23 21:21:03.274706

"""

# revision identifiers, used by Alembic.
revision = '55f8eedef48a'
down_revision = '379e08adff58'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('admin1code', sa.String(length=80), nullable=True))
    op.add_column('location', sa.Column('admin2code', sa.String(length=80), nullable=True))
    op.add_column('location', sa.Column('admin3code', sa.String(length=80), nullable=True))
    op.add_column('location', sa.Column('admin4code', sa.String(length=80), nullable=True))
    op.add_column('location', sa.Column('countryname', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'countryname')
    op.drop_column('location', 'admin4code')
    op.drop_column('location', 'admin3code')
    op.drop_column('location', 'admin2code')
    op.drop_column('location', 'admin1code')
    ### end Alembic commands ###
