"""empty message

Revision ID: 60f33ee2e61
Revises: 44436403ba60
Create Date: 2015-03-17 02:23:30.185038

"""

# revision identifiers, used by Alembic.
revision = '60f33ee2e61'
down_revision = '44436403ba60'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
